### ISSUE TITLE
Dockerhub not showing v1.3.2 as latest image

### ISSUE THREAD

**Issue by charleszlu** [mattikus/docker-murmur#10]
Looking at Docker Hub and it seems like v1.3.2 has been autobuilt correctly, but it is not showing up as an available tag. Also :latest remains on v1.3.1.

**Comment by Do-while-Bacon** [comment]
I'm having the same problem. Pulling down image on latest tag still runs 1.3.1. I'm not very docker savvy. What do I need to do?

**Comment by mattikus** [comment]
Thanks for the report, I'm looking into it. For some reason it built v1.3.2 but hasn't updated the tags on the repo.

**Comment by mattikus** [comment]
I managed to re-tag the image and make sure latest points to the same commit. Can you verify it works?

**Comment by Do-while-Bacon** [comment]
All good now. Thank you!
