### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by Svarto** [mattikus/docker-murmur#13]
Quick q, by default does the murmur create just a self-signed certificate? Or does it leverage LetsEncrypt?

**Comment by mattikus** [comment]
Sorry, I missed this!

I believe murmur by default will use a self-signed certificate. They provide official [instructions on their wiki](https://wiki.mumble.info/wiki/Obtaining_a_Let%27s_Encrypt_Murmur_Certificate) for using a LetsEncrypt cert with murmur.

**Comment by Svarto** [comment]
thanks!
