### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by Nepoxx** [mattikus/docker-murmur#2]
The only error I get is the following: `Couldn't create HUP socketpair`

This is a brand new Ubuntu 16.04 Digital Ocean Droplet

**Comment by mattikus** [comment]
Hey Nepoxx.

How are you running the container? Can you paste the command you used to run it as well as any other logs?

**Comment by Nepoxx** [comment]
Are there any other logs I can look at?

```
nepoxx@ubuntu-16 ~> docker run -d -p 64738:64738 --restart=always -v /data/murmur:/data --name murmur mattikus/murmur
267a0bc8e2924c6b86cd3036687ac436f44deb5f478ba67909734e8599cb3d7f
nepoxx@ubuntu-16 ~> docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                                    PORTS                                 NAMES
267a0bc8e292        mattikus/murmur     "/opt/murmur/murmur.x"   3 seconds ago       Restarting (139) Less than a second ago   64738/udp, 0.0.0.0:64738->64738/tcp   murmur
f6c1aac2504a        ghost               "/entrypoint.sh npm s"   12 days ago         Up 12 days                                                                      ghost-blog
nepoxx@ubuntu-16 ~> docker logs -f murmur
Couldn't create HUP socketpair
Couldn't create HUP socketpair
Couldn't create HUP socketpair
Couldn't create HUP socketpair
Couldn't create HUP socketpair
Couldn't create HUP socketpair
Couldn't create HUP socketpair
```

**Comment by mattikus** [comment]
Hmm. This is strange.

I just created a couple digital ocean droplets both 32bit and 64bit (just in case) and I'm not able to replicate that behavior. I even tried having something listening on that port before I started the container but the error message is different.

The docker container is a veeerry thin wrapper around the static binary available from mumble's github repos. You might try grabbing the tarball from them directly and trying to run the murmur binary without docker, to see if docker is the problem or the binary is the problem.

https://github.com/mumble-voip/mumble/releases/download/1.2.16/murmur-static_x86-1.2.16.tar.bz2

**Comment by Nepoxx** [comment]
Out of curiosity, have you tried with Ubuntu 16.04?

I'll try it out with Ubuntu 14.04 when I get home and try the static binary with 16.04 and report back.

**Comment by mattikus** [comment]
I actually used 16.04, since you mentioned that is what you had used. I haven't tried with 14.04, though I can also try it to compare. I don't expect it will have any issues either, though.

You might also try spinning up a fresh droplet and seeing if it might be a conflict in something else that's installed or configured, though I thought that was what docker and containers were supposed to protect us from 😁

**Comment by Nepoxx** [comment]
I've created a brand new droplet (using docker-machine), used the command I posted above and it worked as expected. Since I can't reproduce it myself (other than on my machine with another single docker container running), I'm going to close this.

For the record, using the binary "natively" (no docker), worked fine. I tried building the container myself and starting with murmur's provided `.ini` file, which resulted in the same issue. I have no clue how to debug this.

**Comment by mattikus** [comment]
That's so strange. Thanks for doing the testing. I've never run into that
before. My gut says it has to do with the setup of that one droplet somehow
but I've got no clue.

Naive googling for that error says it has to do with Qt somehow, but I'm
not sure how that plays into the murmur daemon. Very weird.

If you figure it out, let me know.
