### ISSUE TITLE
Merging efforts...

### ISSUE THREAD

**Issue by sudoforge** [mattikus/docker-murmur#4]
Hey there, I've maintained a murmurd container at [bddenhartog/docker-murmur](https://github.com/bddenhartog/docker-murmur) for a little over a year. My image is based off of the latest stable `alpine`, and comes out a few MB smaller than yours.

The core functionality is all there, along with a few QOL improvements, and the development focus for my own project is geared towards automation -- I suppose what I am suggesting is that we collaborate together instead of maintaining two different versions of essentially the same image.

**Comment by mattikus** [comment]
Thanks for the offer but I'm pretty happy with my project and would prefer to keep it open.
